name: surrah
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Localization
  intl: ^0.20.2
  
  # Icons
  cupertino_icons: ^1.0.8

  # UI
  flutter_svg: ^2.3.0
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^2.0.1

  # State Management & Dependency Injection
  get_it: ^9.2.1
  flutter_bloc: ^8.1.0
  hydrated_bloc: ^9.0.0

  # Local Storage
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development Tools
  rename: ^3.1.0
  flutter_lints: ^6.0.0

  # App Assets
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/appLogo.png"
  adaptive_icon_background: "assets/images/appLogo.png"
  adaptive_icon_foreground: "assets/images/appLogo.png"

flutter_native_splash:
  color: "#010D2F"
  image: assets/images/nativeSplashLogo.png
  android_12:
    color: "#010D2F"
    image: assets/images/nativeSplashLogo.png