name: surrah
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Localization
  intl: ^0.20.2
  
  # Icons
  cupertino_icons: ^1.0.8

  # UI
  lottie: ^3.3.3
  fl_chart: ^1.2.0
  flutter_svg: ^2.3.0
  icon_broken: ^1.1.0
  country_flags: ^4.1.2
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^2.0.1
  font_awesome_flutter: ^11.0.0

  # State Management & Dependency Injection
  get_it: ^9.2.1
  flutter_bloc: ^8.1.0
  hydrated_bloc: ^9.0.0

  # Functional Programming
  dartz: ^0.10.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # External Services
  url_launcher: ^6.3.2
  flex_color_picker: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development Tools
  rename: ^3.1.0
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

  # App Assets
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/fonts/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/appLogo.png"
  adaptive_icon_background: "assets/images/appLogo.png"
  adaptive_icon_foreground: "assets/images/appLogo.png"

flutter_native_splash:
  color: "#010D2F"
  image: assets/images/nativeSplashLogo.png
  android_12:
    color: "#010D2F"
    image: assets/images/nativeSplashLogo.png